GRANT SELECT, INSERT ON `yandi_epistemic`.* TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`belief` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`semantic_edge` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`grievance` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`forgiveness_capacity` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`personality` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`self_state` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`reflection_policy` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`family_status_state` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`knowledge_record` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`peer_config` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`biography` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`context_topic` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`decision_journal_entry` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`experience` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`secret_archive_question` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`inner_state` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`trait_graph` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`self_reflection_profile` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`social_knowledge` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`knowledge_query_archive` TO 'yandi_runtime'@'localhost';
GRANT UPDATE ON `yandi_epistemic`.`verification_run` TO 'yandi_runtime'@'localhost';
FLUSH PRIVILEGES;
